spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=universidades;encrypt=false;instance=SQLEXPRESS01
    username: sa
    password: SQLAdmin!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        naming.physical-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl