server:
  port: 8005
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=universidades;encrypt=false;instance=SQLEXPRESS01
    username: sa
    password: SQLAdmin!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        naming.physical-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000